from __future__ import annotations

from fastapi.testclient import TestClient

from automl_sdk import AutoMLClient

from .helpers import AUTH, create_ready_dataset, create_waiting_run, mutation_headers, run_request


def _create_external_agent_run(client: TestClient, suffix: str) -> dict[str, object]:
    upload = create_ready_dataset(client, suffix)
    request = run_request(str(upload["dataset_version_id"]))
    request["policy"]["allow_external_llm"] = True
    request["budget"]["max_llm_tokens"] = 123
    response = client.post(
        "/v1/runs",
        headers=mutation_headers(f"agent-run-{suffix}"),
        json=request,
    )
    assert response.status_code == 202, response.text
    return response.json()


def test_agent_manifest_declares_an_external_planner_without_an_internal_llm(
    client: TestClient,
) -> None:
    assert client.get("/v1/agent/manifest").status_code == 401

    manifest = client.get("/v1/agent/manifest", headers=AUTH)
    assert manifest.status_code == 200, manifest.text
    body = manifest.json()
    assert body["service_role"] == "AUTOML_EXECUTION_BACKEND"
    assert body["planner_location"] == "EXTERNAL_AGENT_PLATFORM"
    assert body["internal_llm_calls"] is False
    assert body["llm_budget_owner"] == "EXTERNAL_AGENT_PLATFORM"
    assert body["max_llm_tokens_consumed"] is False
    assert body["credentials_must_remain_in_platform"] is True
    assert body["production_external_llm_safe"] is False
    assert body["service_version"] == "0.7.0"
    assert body["api_version"] == "v1"
    assert body["agent_tools_openapi_href"] == "/v1/agent/tool-openapi.yaml"
    assert len(body["agent_tools_openapi_sha256"]) == 64
    assert body["operation_scopes"]["answerDecisionPacket"] == (
        "automl:operation:answerDecisionPacket"
    )
    assert body["default_backend_id"] == "sklearn"
    backends = {item["backend_id"]: item for item in body["backends"]}
    assert backends["sklearn"]["status"] == "AVAILABLE"
    assert backends["sklearn"]["available"] is True
    assert backends["sklearn"]["production_eligible"] is False
    assert backends["sklearn"]["capabilities"]["task_types"] == [
        "BINARY_CLASSIFICATION",
        "REGRESSION",
    ]
    tabpfn_attributions = backends["tabpfn"]["capabilities"]["required_attributions"]
    assert tabpfn_attributions == ["Built with PriorLabs-TabPFN"]
    assert backends["sklearn"]["artifact"]["serialization"] == "joblib"
    assert "internal_llm_planning" in body["unsupported_capabilities"]
    assert body["runtime_limits"]["max_trials_per_run"] >= 2
    sklearn_backend = next(
        backend for backend in body["backends"] if backend["backend_id"] == "sklearn"
    )
    assert sklearn_backend["installed"] is True
    assert sklearn_backend["available"] is True
    assert "answerDecisionPacket" in body["canonical_operation_ids"]
    assert "answerDecisionPacket" in body["active_operation_ids"]
    assert body["context_path_template"] == "/v1/runs/{run_id}/agent-context"

    tools_contract = client.get("/v1/agent/tool-openapi.yaml", headers=AUTH)
    assert tools_contract.status_code == 200, tools_contract.text
    assert tools_contract.text.startswith("# Generated by scripts/generate_agent_openapi.py")


def test_agent_context_is_policy_gated_and_reuses_canonical_commands(
    client: TestClient,
) -> None:
    denied = create_waiting_run(client, "agent-denied-0001")
    denied_context = client.get(
        f"/v1/runs/{denied['run_id']}/agent-context",
        headers=AUTH,
    )
    assert denied_context.status_code == 403
    assert denied_context.json()["code"] == "external_agent_access_denied"

    run = _create_external_agent_run(client, "agent-allowed-0001")
    run_id = str(run["run_id"])
    context_response = client.get(
        f"/v1/runs/{run_id}/agent-context",
        headers=AUTH,
    )
    assert context_response.status_code == 200, context_response.text
    assert context_response.headers["cache-control"] == "private, no-cache"
    context = context_response.json()
    assert context["run"]["status"] == "WAITING_USER"
    assert context["contains_raw_dataset_rows"] is False
    assert context["may_include_dataset_derived_values"] is True
    assert context["dataset_derived_text_trust"] == "UNTRUSTED"
    assert context["run"]["budget_usage"]["llm_tokens"] == {"used": 0, "limit": 123}
    assert context["event_checkpoint"] == {
        "after_seq": context["run"]["snapshot_seq"],
        "events_href": f"/v1/runs/{run_id}/events",
    }
    assert len(context["open_decision_packets"]) == 1
    packet = context["open_decision_packets"][0]
    assert packet["resolution_policy"] == "HUMAN_REQUIRED"
    question = packet["questions"][0]
    assert question["selection_mode"] == "FREEFORM"
    assert question["min_selections"] == question["max_selections"] == 1

    unchanged = client.get(
        f"/v1/runs/{run_id}/agent-context",
        headers={**AUTH, "If-None-Match": context_response.headers["etag"]},
    )
    assert unchanged.status_code == 304

    actions_response = client.get(f"/v1/runs/{run_id}/agent-actions", headers=AUTH)
    assert actions_response.status_code == 200, actions_response.text
    actions = actions_response.json()["items"]
    # This packet is a human gate. The external Agent receives the context but
    # cannot mistake the canonical answer endpoint for an executable Agent action.
    assert {item["action"] for item in actions} == {"PAUSE", "CANCEL"}

    answer_href = f"/v1/runs/{run_id}/decision-packets/{packet['wait_set_id']}:answer"
    answered = client.post(
        answer_href,
        headers=mutation_headers(
            "agent-answer-allowed-0001",
            **{"If-Match": f'"{packet["wait_set_revision"]}"'},
        ),
        json={"answers": [{"question_id": "q_target", "value": "label"}]},
    )
    assert answered.status_code == 202, answered.text

    terminal_context = client.get(
        f"/v1/runs/{run_id}/agent-context",
        headers=AUTH,
        params={"output_limit": 1},
    ).json()
    assert terminal_context["run"]["status"] == "TERMINAL"
    assert terminal_context["result_available"] is True
    assert terminal_context["output_refs_truncated"] is True
    assert client.get(f"/v1/runs/{run_id}/agent-actions", headers=AUTH).json()["items"] == []

    hidden = client.get(
        f"/v1/runs/{run_id}/agent-context",
        headers={"Authorization": "Bearer another-agent-tenant"},
    )
    assert hidden.status_code == 404

    hidden_actions = client.get(
        f"/v1/runs/{run_id}/agent-actions",
        headers={"Authorization": "Bearer another-agent-tenant"},
    )
    assert hidden_actions.status_code == 404

    denied_actions = client.get(
        f"/v1/runs/{denied['run_id']}/agent-actions",
        headers=AUTH,
    )
    assert denied_actions.status_code == 403
    assert denied_actions.json()["code"] == "external_agent_access_denied"


def test_sdk_reads_the_external_agent_integration_surface(client: TestClient) -> None:
    run = _create_external_agent_run(client, "agent-sdk-0001")
    sdk = AutoMLClient("http://testserver", token="test-tenant-token", http_client=client)

    manifest = sdk.get_agent_manifest()
    context = sdk.get_agent_context(str(run["run_id"]), output_limit=1)
    actions = sdk.list_agent_actions(str(run["run_id"]))

    assert manifest["internal_llm_calls"] is False
    assert context is not None and context["run"]["run_id"] == run["run_id"]
    assert {item["action"] for item in actions["items"]} == {"PAUSE", "CANCEL"}
