#!/usr/bin/env python3
"""Generate the active Agent tool contract from the canonical OpenAPI file."""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path


ACTIVE_OPERATION_IDS = (
    "getAgentInterfaceManifest",
    "getAgentRunContext",
    "listAgentRunActions",
    "createDatasetUpload",
    "signDatasetUploadParts",
    "finalizeDatasetUpload",
    "getDatasetVersion",
    "createRun",
    "getRun",
    "readRunEvents",
    "listRunOutputs",
    "getRunOutput",
    "listDecisionPackets",
    "answerDecisionPacket",
    "pauseRun",
    "resumeRun",
    "cancelRun",
    "getCommand",
    "getRunResult",
    "getArtifact",
    "createArtifactDownloadTicket",
)

HTTP_METHODS = frozenset({"get", "put", "post", "delete", "options", "head", "patch", "trace"})
GENERATED_NOTICE = (
    "# Generated by scripts/generate_agent_openapi.py from openapi/automl-api.yaml.\n"
    "# Do not edit this file directly.\n"
)
_PATH_HEADER = re.compile(r"^  (?P<path>\S.*):\s*$")
_CHILD_HEADER = re.compile(r"^    (?P<key>[A-Za-z][A-Za-z0-9_-]*):\s*$")
_OPERATION_ID = re.compile(
    r"^      operationId:\s*(?P<operation_id>[A-Za-z][A-Za-z0-9_]*)\s*$",
    re.MULTILINE,
)


@dataclass(frozen=True)
class OperationLocation:
    path: str
    method: str
    operation_id: str


def _contract_sections(contract: str) -> tuple[str, str, str]:
    paths_marker = "paths:\n"
    components_marker = "\ncomponents:\n"
    paths_start = contract.find(paths_marker)
    if paths_start < 0:
        raise ValueError("canonical contract has no top-level paths section")
    paths_body_start = paths_start + len(paths_marker)
    components_start = contract.find(components_marker, paths_body_start)
    if components_start < 0:
        raise ValueError("canonical contract has no top-level components section")
    return (
        contract[:paths_body_start],
        contract[paths_body_start:components_start],
        contract[components_start:],
    )


def _segments(
    lines: list[str], pattern: re.Pattern[str]
) -> tuple[list[str], list[tuple[re.Match[str], list[str]]]]:
    starts = [(index, match) for index, line in enumerate(lines) if (match := pattern.match(line))]
    if not starts:
        return lines, []
    preamble = lines[: starts[0][0]]
    segments: list[tuple[re.Match[str], list[str]]] = []
    for position, (start, match) in enumerate(starts):
        end = starts[position + 1][0] if position + 1 < len(starts) else len(lines)
        segments.append((match, lines[start:end]))
    return preamble, segments


def _decode_path(value: str) -> str:
    if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
        return value[1:-1]
    return value


def _path_entries(paths_body: str) -> tuple[list[str], list[tuple[str, list[str]]]]:
    preamble, raw_entries = _segments(paths_body.splitlines(keepends=True), _PATH_HEADER)
    entries = [(_decode_path(match.group("path")), lines) for match, lines in raw_entries]
    return preamble, entries


def _operation_from_child(path: str, key: str, lines: list[str]) -> OperationLocation | None:
    if key not in HTTP_METHODS:
        return None
    operation_ids = _OPERATION_ID.findall("".join(lines))
    if len(operation_ids) != 1:
        raise ValueError(f"{key.upper()} {path} must declare exactly one operationId")
    return OperationLocation(path=path, method=key, operation_id=operation_ids[0])


def parse_operations(contract: str) -> list[OperationLocation]:
    """Return every OpenAPI operation without requiring a YAML dependency."""

    _, paths_body, _ = _contract_sections(contract)
    _, path_entries = _path_entries(paths_body)
    operations: list[OperationLocation] = []
    for path, path_lines in path_entries:
        _, children = _segments(path_lines[1:], _CHILD_HEADER)
        for child_match, child_lines in children:
            operation = _operation_from_child(path, child_match.group("key"), child_lines)
            if operation is not None:
                operations.append(operation)
    return operations


def render_agent_contract(canonical: str) -> str:
    """Filter the canonical contract to the allowlisted, currently implemented operations."""

    prefix, paths_body, components = _contract_sections(canonical)
    path_preamble, path_entries = _path_entries(paths_body)
    wanted = set(ACTIVE_OPERATION_IDS)
    selected: dict[str, OperationLocation] = {}
    rendered_paths = list(path_preamble)

    for path, path_lines in path_entries:
        child_preamble, children = _segments(path_lines[1:], _CHILD_HEADER)
        kept_children: list[str] = []
        has_selected_operation = False
        for child_match, child_lines in children:
            key = child_match.group("key")
            operation = _operation_from_child(path, key, child_lines)
            if operation is None:
                kept_children.extend(child_lines)
                continue
            if operation.operation_id not in wanted:
                continue
            if operation.operation_id in selected:
                raise ValueError(f"duplicate active operationId: {operation.operation_id}")
            selected[operation.operation_id] = operation
            has_selected_operation = True
            kept_children.extend(child_lines)

        if has_selected_operation:
            rendered_paths.extend(path_lines[:1])
            rendered_paths.extend(child_preamble)
            rendered_paths.extend(kept_children)

    missing = wanted.difference(selected)
    if missing:
        raise ValueError(
            f"active operationId values missing from canonical contract: {sorted(missing)}"
        )

    active_prefix = prefix.replace(
        "  title: Managed AutoML API\n",
        "  title: Managed AutoML Agent Tools API\n",
        1,
    )
    if active_prefix == prefix:
        raise ValueError("canonical info.title changed; update the generator deliberately")
    return GENERATED_NOTICE + active_prefix + "".join(rendered_paths) + components


def _parser() -> argparse.ArgumentParser:
    root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--source",
        type=Path,
        default=root / "openapi" / "automl-api.yaml",
        help="canonical OpenAPI input",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=root / "openapi" / "automl-agent-tools.yaml",
        help="generated active Agent tool contract",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the checked-in output differs from a fresh generation",
    )
    return parser


def main() -> int:
    args = _parser().parse_args()
    rendered = render_agent_contract(args.source.read_text(encoding="utf-8"))
    if args.check:
        if not args.output.exists() or args.output.read_text(encoding="utf-8") != rendered:
            print(f"{args.output} is stale; run {Path(__file__).name}", file=sys.stderr)
            return 1
        print(f"{args.output} is up to date")
        return 0
    args.output.write_text(rendered, encoding="utf-8")
    print(f"wrote {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
